# Exercício 1

In [51]:
import numpy as np
M = np.random.rand(4,4)
np.save ('saved-matrix.npy', M)
np.load ('saved-matrix.npy')
print (M)


[[ 0.89442926  0.89319683  0.71163812  0.8271876 ]
 [ 0.57217697  0.24012011  0.64037963  0.10028343]
 [ 0.29342458  0.60591916  0.40099509  0.15892517]
 [ 0.48057442  0.03306498  0.73012837  0.19894514]]
